title: Calum Mackervoy
email: c.mackervoy@gmail.com
description: Professional website of Calum Mackervoy
baseurl: ""
#url: "http://localhost:4000"
url: "https://calum.mackervoy.com"
twitter_username: calummackervoy
github_username:  calummackervoy
itch_url: https://calummackervoy.itch.io/

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  projects:
    output: false
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

languages:
  en:
    label: English
  fr:
    label: Français
  es:
    label: Español

exclude:
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
